{
 "title": "MultiView",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(node_exporter_build_info, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 0 }, "repeat": "host" },
  { "title": "$host", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 0 } },
  { "title": "$host", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$host\"} - node_boot_time_seconds{instance=~\"$host\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$host\"} - node_boot_time_seconds{instance=~\"$host\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$host\"} - node_boot_time_seconds{instance=~\"$host\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$host\", mountpoint=\"/\"} - node_filesystem_free_bytes{instance=~\"$host\", mountpoint=\"/\"})/1000000000",
     "legendFormat": "/ Used"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$host\", mountpoint=\"/\"}/1000000000",
     "legendFormat": "/ Total"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$host\", mountpoint=\"/\"} - node_filesystem_free_bytes{instance=~\"$host\", mountpoint=\"/\"})/1000000000",
     "legendFormat": "/ Used"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$host\", mountpoint=\"/\"}/1000000000",
     "legendFormat": "/ Total"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$host\", mountpoint=\"/\"} - node_filesystem_free_bytes{instance=~\"$host\", mountpoint=\"/\"})/1000000000",
     "legendFormat": "/ Used"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$host\", mountpoint=\"/\"}/1000000000",
     "legendFormat": "/ Total"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"cpu-thermal\",zone=\"0\",instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"cpu-thermal\",zone=\"0\",instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"cpu-thermal\",zone=\"0\",instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$host\"} - node_memory_MemAvailable_bytes{instance=\"$host\"})/1000000",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"}/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$host\"} - node_memory_MemAvailable_bytes{instance=\"$host\"})/1000000",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"}/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$host\"} - node_memory_MemAvailable_bytes{instance=\"$host\"})/1000000",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"}/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$host\"} - node_memory_MemAvailable_bytes{instance=\"$host\"})/1000000",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$host\"} - node_memory_MemAvailable_bytes{instance=\"$host\"})/1000000",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$host\"} - node_memory_MemAvailable_bytes{instance=\"$host\"})/1000000",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU Usage based on cpu work minus idle time",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{instance=~\"$host\",mode=\"idle\"}[5m]) * 100) ",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU Usage based on cpu work minus idle time",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{instance=~\"$host\",mode=\"idle\"}[5m]) * 100) ",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU Usage based on cpu work minus idle time",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{instance=~\"$host\",mode=\"idle\"}[5m]) * 100) ",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$host\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$host\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$host\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Top 10 Processes by Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, mem_usage{instance=\"piirc\"})",
     "legendFormat": "{{process}} - {{pid}}"
    }
   ]
  },
  {
   "title": "Top 10 Processes by CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, cpu_usage{instance=\"piirc\"})",
     "legendFormat": "{{process}} - {{pid}}"
    }
   ]
  }
 ]
}